# Generated by Django 5.2.17 on 2026-09-22 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0002_uploadedimage_max_retries_uploadedimage_retry_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('gate', 'Gate Camera')], db_index=True, default='upload', help_text='Gate camera frames are excluded from the public image endpoints.', max_length=10, verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_normalized', models.CharField(editable=False, max_length=20, unique=True)),
                ('plate_display', models.CharField(max_length=32, verbose_name='Plate Number')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('other', 'Other')], default='car', max_length=16)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate_normalized'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('host', models.CharField(max_length=255)),
                ('rtsp_port', models.PositiveIntegerField(default=554, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('http_port', models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password_encrypted', models.TextField(blank=True, editable=False)),
                ('vendor', models.CharField(choices=[('hikvision', 'Hikvision'), ('dahua', 'Dahua'), ('generic', 'Generic')], default='generic', max_length=16)),
                ('main_stream_path', models.CharField(blank=True, max_length=255)),
                ('sub_stream_path', models.CharField(blank=True, max_length=255)),
                ('snapshot_path', models.CharField(blank=True, max_length=255)),
                ('prefer_snapshot', models.BooleanField(default=True)),
                ('roi_x', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('roi_y', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('roi_w', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('roi_h', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('motion_threshold', models.FloatField(default=0.02, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('settle_ms', models.PositiveIntegerField(default=800)),
                ('cooldown_s', models.PositiveIntegerField(default=5)),
                ('config_version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_test_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, editable=False, null=True)),
                ('last_test_error', models.TextField(blank=True, editable=False)),
                ('agent_status', models.CharField(blank=True, editable=False, max_length=20)),
                ('agent_status_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GateDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], default='in', max_length=4)),
                ('controller_url', models.URLField(blank=True)),
                ('controller_token_encrypted', models.TextField(blank=True, editable=False)),
                ('has_safety_input', models.BooleanField(default=False, help_text="A loop detector or IR beam is wired to the barrier controller's safety input.")),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, editable=False, null=True)),
                ('firmware_version', models.CharField(blank=True, editable=False, max_length=50)),
                ('last_command_result', models.CharField(blank=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates', to='lpr_app.camera')),
            ],
            options={
                'verbose_name': 'Gate Device',
                'verbose_name_plural': 'Gate Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plate_raw', models.CharField(blank=True, max_length=64)),
                ('plate_normalized', models.CharField(blank=True, db_index=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('frames_read', models.PositiveIntegerField(default=0)),
                ('frames_agreed', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('manual', 'Manual')], db_index=True, max_length=10)),
                ('reason', models.CharField(choices=[('whitelist_hit', 'Registered vehicle'), ('no_plate', 'No plate detected'), ('no_consensus', 'Frames disagree'), ('low_confidence', 'Low confidence'), ('not_registered', 'Not registered'), ('expired', 'Registration expired'), ('not_yet_valid', 'Registration not yet valid'), ('inactive', 'Registration inactive'), ('device_disabled', 'Gate disabled'), ('inference_timeout', 'Recognition timed out'), ('processing_error', 'Recognition failed'), ('manual_override', 'Manual override')], db_index=True, max_length=24)),
                ('mode', models.CharField(default='shadow', max_length=10)),
                ('command', models.CharField(blank=True, max_length=10)),
                ('command_sent', models.BooleanField(default=False)),
                ('command_result', models.CharField(blank=True, max_length=100)),
                ('decision_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='lpr_app.uploadedimage')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='lpr_app.gatedevice')),
                ('near_miss_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='near_miss_events', to='lpr_app.vehicle')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='lpr_app.vehicle')),
            ],
            options={
                'verbose_name': 'Access Event',
                'verbose_name_plural': 'Access Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GateConfigChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Config Change',
                'verbose_name_plural': 'Gate Config Changes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='lpr_app_gat_object__0479cb_idx')],
            },
        ),
    ]
