# Generated by Django 5.2.17 on 2026-09-22 10:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0004_gate_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Created from the admin gate test page, not by a vehicle at the gate.'),
        ),
        migrations.AddField(
            model_name='gatedevice',
            name='arm_state',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('moving', 'Moving'), ('stopped', 'Stopped'), ('unknown', 'Unknown')], editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='gatedevice',
            name='arm_state_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gatedevice',
            name='controller_type',
            field=models.CharField(choices=[('esp32', 'ESP32 relay controller'), ('simulator', 'Simulated barrier (no hardware)')], default='esp32', help_text='A simulated barrier receives commands even in shadow mode, since it moves no hardware.', max_length=10),
        ),
        migrations.CreateModel(
            name='SimulatedBarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_seconds', models.FloatField(default=3.0, help_text='Time for the arm to travel fully up or down.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(60.0)])),
                ('auto_close_seconds', models.PositiveIntegerField(default=10, help_text="Close automatically this long after reaching the top, like the controller's TIMING setting. 0 disables.")),
                ('phase', models.CharField(choices=[('down', 'Down'), ('moving_up', 'Moving up'), ('up', 'Up'), ('moving_down', 'Moving down'), ('stopped', 'Stopped')], default='down', editable=False, max_length=12)),
                ('phase_started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('start_position', models.FloatField(default=0.0, editable=False)),
                ('last_nonce', models.BigIntegerField(default=0, editable=False)),
                ('last_motion_command', models.CharField(blank=True, editable=False, max_length=10)),
                ('last_motion_command_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history', models.JSONField(blank=True, default=list, editable=False)),
                ('gate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulator', to='lpr_app.gatedevice')),
            ],
            options={
                'verbose_name': 'Simulated Barrier',
                'verbose_name_plural': 'Simulated Barriers',
            },
        ),
    ]
