# Generated by Django 5.2.17 on 2026-09-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0005_gate_simulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='live_snapshot_path',
            field=models.CharField(blank=True, help_text='Snapshot path for the live monitoring view; usually the sub-stream, which is cheaper for the camera. Empty uses the path above.', max_length=255),
        ),
    ]
