# Generated by Django 5.2.17 on 2026-09-23 07:07, then reordered by hand so the
# camera each gate already has is carried into GateCamera before the old field
# is dropped.

import django.db.models.deletion
from django.db import migrations, models


def copy_camera_to_link(apps, schema_editor):
    """The gate's single camera becomes a link watching the gate's direction."""
    GateDevice = apps.get_model('lpr_app', 'GateDevice')
    GateCamera = apps.get_model('lpr_app', 'GateCamera')
    links = [
        GateCamera(gate_id=gate.pk, camera_id=gate.camera_id, direction=gate.direction or 'in')
        for gate in GateDevice.objects.exclude(camera_id=None)
    ]
    GateCamera.objects.bulk_create(links)


def link_back_to_camera(apps, schema_editor):
    """Reverse: keep the first camera of each gate, preferring the entry one."""
    GateDevice = apps.get_model('lpr_app', 'GateDevice')
    GateCamera = apps.get_model('lpr_app', 'GateCamera')
    for gate in GateDevice.objects.all():
        link = (GateCamera.objects.filter(gate_id=gate.pk).order_by('direction', 'id').first())
        if link is not None:
            gate.camera_id = link.camera_id
            gate.direction = link.direction
            gate.save(update_fields=['camera_id', 'direction'])


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0006_camera_live_snapshot_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Entry'), ('out', 'Exit')], default='in', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_links', to='lpr_app.camera')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_cameras', to='lpr_app.gatedevice')),
            ],
            options={
                'verbose_name': 'Gate Camera',
                'verbose_name_plural': 'Gate Cameras',
                'ordering': ['direction', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gatecamera',
            constraint=models.UniqueConstraint(fields=('gate', 'camera'), name='unique_gate_camera'),
        ),
        migrations.RunPython(copy_camera_to_link, link_back_to_camera),
        migrations.RemoveField(
            model_name='gatedevice',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='gatedevice',
            name='direction',
        ),
        migrations.AddField(
            model_name='gatedevice',
            name='cameras',
            field=models.ManyToManyField(blank=True, related_name='gates', through='lpr_app.GateCamera', to='lpr_app.camera'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='lpr_app.camera'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='direction',
            field=models.CharField(blank=True, choices=[('in', 'Entry'), ('out', 'Exit')], help_text='Which way the vehicle was going, from the camera that read it.', max_length=4),
        ),
        migrations.AddField(
            model_name='gatedevice',
            name='exit_policy',
            field=models.CharField(choices=[('registered', 'Only registered vehicles'), ('any', 'Every vehicle (plates are still read and logged)')], default='registered', help_text='What happens when a camera watching the exit reads a vehicle. "Every vehicle" still reads and logs the plate, but opens regardless.', max_length=12),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='reason',
            field=models.CharField(choices=[('whitelist_hit', 'Registered vehicle'), ('no_plate', 'No plate detected'), ('no_consensus', 'Frames disagree'), ('low_confidence', 'Low confidence'), ('not_registered', 'Not registered'), ('expired', 'Registration expired'), ('not_yet_valid', 'Registration not yet valid'), ('inactive', 'Registration inactive'), ('device_disabled', 'Gate disabled'), ('inference_timeout', 'Recognition timed out'), ('processing_error', 'Recognition failed'), ('manual_override', 'Manual override'), ('exit_free', 'Exit open to every vehicle')], db_index=True, max_length=24),
        ),
    ]
