# Generated by Django 5.2.17 on 2026-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0007_gate_multi_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='agent_trigger',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='What the agent last measured on this camera: frame rate, and the motion and presence scores against their thresholds. Shows why a vehicle did or did not start a recognition burst.'),
        ),
    ]
