# Generated by Django 5.2.17 on 2026-09-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0008_camera_agent_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='frames',
            field=models.ManyToManyField(blank=True, help_text='Every frame of the burst that was kept, including the one above. Which ones survive is set by GATE_KEEP_FRAMES.', related_name='frame_events', to='lpr_app.uploadedimage'),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='uploaded_image',
            field=models.ForeignKey(blank=True, help_text='The frame the plate was read from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='lpr_app.uploadedimage'),
        ),
    ]
