# Generated by Django 5.2.17 on 2026-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0009_event_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='travel_direction',
            field=models.CharField(choices=[('any', 'Every vehicle'), ('toward', 'Vehicles coming toward the camera'), ('away', 'Vehicles going away from the camera')], default='any', help_text='Which vehicles this camera reads. When two cameras watch the same lane from either end, each sees every vehicle; reading only those coming toward it gives one event per vehicle, in the right direction, with its front plate.', max_length=8),
        ),
    ]
