# Generated by Django 5.2.17 on 2026-09-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0010_camera_travel_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatedevice',
            name='controller_health',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='What the controller last reported about itself: transport (relay or rf433), WiFi signal (dBm), whether its clock is synced, radio transmissions, dry run.'),
        ),
        migrations.AlterField(
            model_name='gatedevice',
            name='controller_type',
            field=models.CharField(choices=[('esp32', 'ESP32 relay controller'), ('esp32_rf', 'ESP32 + 433 MHz remote'), ('simulator', 'Simulated barrier (no hardware)')], default='esp32', help_text='A simulated barrier receives commands even in shadow mode, since it moves no hardware.', max_length=10),
        ),
    ]
