# Generated by Django 5.2.17 on 2026-09-29 01:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0011_gate_controller_rf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('capture', 'Capture a remote button'), ('save_code', 'Keep the captured code')], max_length=10)),
                ('button', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN'), ('stop', 'STOP')], max_length=5)),
                ('seconds', models.PositiveSmallIntegerField(default=6, help_text='How long a capture listens.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(15)])),
                ('state', models.CharField(choices=[('queued', 'Waiting for the agent'), ('dispatched', 'Taken by the agent'), ('running', 'Controller listening'), ('done', 'Done'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=10)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_jobs', to='lpr_app.gatedevice')),
            ],
            options={
                'verbose_name': 'Controller Job',
                'verbose_name_plural': 'Controller Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
