# Generated by Django 5.2.17 on 2026-09-30 15:56

import lpr_app.utils.time_windows
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0012_controller_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatedevice',
            name='approach_hours',
            field=models.CharField(blank=True, help_text='When opening on approach applies, e.g. "06:30-08:00, 16:30-18:00" (TIME_ZONE); a window may cross midnight ("22:00-06:00"). Empty: all day.', max_length=100, validators=[lpr_app.utils.time_windows.validate_time_windows]),
        ),
        migrations.AddField(
            model_name='gatedevice',
            name='approach_open',
            field=models.CharField(choices=[('off', 'Off: every vehicle is read first'), ('in', 'Vehicles arriving'), ('out', 'Vehicles leaving'), ('both', 'Vehicles arriving and leaving')], default='off', help_text='Open as soon as a vehicle is seen coming toward a camera of these directions, before its plate is read. The plate is still read and logged on the same event.', max_length=4),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='reason',
            field=models.CharField(choices=[('whitelist_hit', 'Registered vehicle'), ('no_plate', 'No plate detected'), ('no_consensus', 'Frames disagree'), ('low_confidence', 'Low confidence'), ('not_registered', 'Not registered'), ('expired', 'Registration expired'), ('not_yet_valid', 'Registration not yet valid'), ('inactive', 'Registration inactive'), ('device_disabled', 'Gate disabled'), ('inference_timeout', 'Recognition timed out'), ('processing_error', 'Recognition failed'), ('manual_override', 'Manual override'), ('exit_free', 'Exit open to every vehicle'), ('approach_open', 'Opened on approach')], db_index=True, max_length=24),
        ),
    ]
