# Generated by Django 5.2.17 on 2026-10-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0013_gate_approach_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_display', models.CharField(max_length=32, verbose_name='Plate Number')),
                ('plate_normalized', models.CharField(editable=False, max_length=20, unique=True)),
                ('label', models.CharField(blank=True, help_text='Shown in the message, e.g. "Director\'s car".', max_length=100)),
                ('directions', models.CharField(choices=[('both', 'Arriving and leaving'), ('in', 'Arriving'), ('out', 'Leaving')], default='both', max_length=4)),
                ('chat_ids', models.CharField(blank=True, help_text='Telegram chat ids for this plate, separated by commas. Empty: TELEGRAM_CHAT_IDS.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plate Alert',
                'verbose_name_plural': 'Plate Alerts',
                'ordering': ['plate_normalized'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=8)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='lpr_app.accessevent')),
                ('alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='lpr_app.platealert')),
            ],
            options={
                'verbose_name': 'Alert Delivery',
                'verbose_name_plural': 'Alert Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
