# Generated by Django 5.2.17 on 2026-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0014_plate_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatedevice',
            name='auto_open',
            field=models.BooleanField(default=True, help_text='Off: plates are still read, decided and logged, but the gate is never opened by itself (neither on a registered plate nor on approach). Manual commands still work.', verbose_name='Open automatically'),
        ),
    ]
