# Generated by Django 5.2.17 on 2026-10-02 09:04

import django.db.models.deletion
import lpr_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpr_app', '0015_gate_auto_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerjob',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='controllerjob',
            name='button',
            field=models.CharField(blank=True, choices=[('up', 'UP'), ('down', 'DOWN'), ('stop', 'STOP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='controllerjob',
            name='kind',
            field=models.CharField(choices=[('capture', 'Capture a remote button'), ('save_code', 'Keep the captured code'), ('update', 'Update the firmware')], max_length=10),
        ),
        migrations.CreateModel(
            name='ControllerFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lpr_app.models.firmware_upload_path)),
                ('version', models.CharField(max_length=64)),
                ('board', models.CharField(max_length=16)),
                ('chip', models.CharField(max_length=16)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controller Firmware',
                'verbose_name_plural': 'Controller Firmware',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='controllerjob',
            name='firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='lpr_app.controllerfirmware'),
        ),
    ]
